Feat/forms-model
Solvro/backend-eventownik pull request #22
Opened 2024-12-13 13:30 UTC by Skiperpol

2024-12-15 20:19 UTC, dawidlinek requested changes
@Skiperpol jedna relacja do poprawy, ale ogólnie super

2025-01-02 16:23 UTC, dawidlinek commented
@Skiperpol  bump

2025-01-02 17:03 UTC, Skiperpol commented
Naniosłem zmiany

2025-01-02 18:19 UTC, dawidlinek approved these changes
Super, można przejść do cruda

2025-01-02 18:19 UTC, merged