feat: Added Attribute and ParticipantAttribute models
Solvro/backend-eventownik pull request #27
Opened 2024-12-15 17:57 UTC by karbowskijakub

2024-12-15 20:10 UTC, dawidlinek requested changes
@karbowskijakub tutaj do poprawy relacja atrybutu uczestnika. 

Plus relacja manyToMany z Formularzami

Dodatkowo atrybut może mieć jeden rootBlockId, więc to też jest relacja. Możesz zostawić zakomentowaną na razie, ale niech się pojawi. 
 
No i relacja do eventu, bo Atrybut należy do danego eventu

2024-12-15 20:10 UTC, dawidlinek commented on app/models/attribute.ts
> +  public participantAttributes: HasMany<typeof ParticipantAttribute>
To jest relacja many to many, więc nie robimy modelu dla tabeli pośredniczącej https://lucid.adonisjs.com/docs/relationships#manytomany a value użyjemy jako pivotColumn

2025-01-02 16:23 UTC, dawidlinek commented
@karbowskijakub bump

2025-01-02 18:22 UTC, dawidlinek requested changes
@karbowskijakub  relacja many to many jeszcze wymaga poprawy, ale już wygląda coraz lepiej

2025-01-22 15:58 UTC, dawidlinek commented
@karbowskijakub

2025-02-20 18:38 UTC, dawidlinek commented
@GOLDER303 jeśli to nie będzie potrzebne to można zamknąć

2025-02-20 19:21 UTC, GOLDER303 commented
Zamykamy, bo modele zostały zrobione w #81

2025-02-20 19:21 UTC, closed without merging