feat/admin-models
Solvro/backend-eventownik pull request #28
Opened 2024-12-18 19:26 UTC by GOLDER303

2025-01-02 16:21 UTC, dawidlinek requested changes
@GOLDER303 dodaj proszę relację do eventu, bo przez admin_premission możemy również przejść do wydarzeń danego admina, a to bardziej nam się przyda.

2025-01-03 16:55 UTC, GOLDER303 commented
@dawidlinek czyli mam stworzyć osobny model do tabeli admin_permissions? Bo jak na razie to przez admina można się dostać do event_id, bo jest ustawione jako pivot column, ale nie mam pojęcia, czy da się w ten sposób dostać do modelu eventu.

2025-01-03 18:00 UTC, dawidlinek commented
> @dawidlinek czyli mam stworzyć osobny model do tabeli admin_permissions? Bo jak na razie to przez admina można się dostać do event_id, bo jest ustawione jako pivot column, ale nie mam pojęcia, czy da się w ten sposób dostać do modelu eventu.

@GOLDER303 nie trzeba dodatkowego modelu, relacja analogiczna do uprawnień 
Tak jak do uprawnienia
 @manyToMany(() => Event, {
    pivotTable: "admin_permissions",
    pivotColumns: ["permissionId"],
  })
  declare event: ManyToMany<typeof Event>;

2025-01-03 18:26 UTC, GOLDER303 commented
@dawidlinek genialne, nie wiem dlaczego ja o tym nie pomyślałem. Dzięki za pomoc.

2025-01-05 11:51 UTC, dawidlinek requested changes
@GOLDER303 już dużo lepiej to wygląda. 2 małe zmian i będzie można mergować

2025-01-05 11:51 UTC, dawidlinek commented on app/controllers/participants_controller.ts
> +      }
Nie ma potrzeby na taki zabieg, jeśli nie będzie uczestników to i tak zwróci się pusta tablica.

2025-01-05 11:51 UTC, dawidlinek commented on app/models/admin.ts
> +    pivotColumns: ["permissionId"],
Zastanawiam się czy pivotColumns nie powinny być snake_case

2025-01-05 11:57 UTC, GOLDER303 commented on app/controllers/participants_controller.ts
> +      }
To jest zmiana kogoś innego, którą przez przypadek wciągnąłem do tego PR'a

2025-01-05 11:59 UTC, GOLDER303 commented on app/models/admin.ts
> +    pivotColumns: ["permissionId"],
W dokumentacji nie mogłem nic na ten temat znaleźć, ale na [Adocast'cie](https://adocasts.com/lessons/defining-many-to-many-relationships-and-pivot-columns) rzeczywiście używają snake case

2025-01-05 12:02 UTC, dawidlinek approved these changes
Super, dzięki za sprawne poprawki

2025-01-05 12:02 UTC, merged